### ISSUE TITLE
After running cli setup, commits are by "Travis-CI"

### ISSUE THREAD

**Issue by gr2m** [semantic-release/cli#24] opened 2015-09-02 15:50 UTC
see https://github.com/gr2m/humble-localstorage/commits/master

Any idea how that could have happened? I'm puzzled

**Comment by boennemann** [comment] 2015-09-02 18:02
Uhm, _super_ weird. These commit were created locally by you?

**Comment by gr2m** [comment] 2015-09-02 18:14
yes, they were. Note that I upgraded this repo from a pretty old version of semantic-release, not sure if this has anything to do with it

**Comment by boennemann** [comment] 2015-09-12 13:58
I couldn't reproduce this in any way. I think it might related to this: https://github.com/gr2m/humble-localstorage/blob/master/package.json#L51-L54

I'm closing this for now. I'll happily reopen as soon as we have more evidence that this was caused by semantic-release.

**Closed by boennemann** 2015-09-12 13:58 UTC
