### ISSUE TITLE
Has anyone noticed the non-well-formed `<a name"...">` tag in the release notes?

### ISSUE THREAD

**Issue by uglow** [semantic-release/cli#103] opened 2017-01-23 12:37 UTC
See [releases](https://github.com/semantic-release/cli/releases) for an example. The anchor tag is missing an `=` for the `name` attribute. E.g. `<a name"...">` instead of `<a name="...">`

**Comment by ethanneff** [comment] 2017-07-13 21:54
related https://github.com/semantic-release/semantic-release/issues/363

**Comment by pvdlg** [comment] 2017-12-16 22:10
Duplicate of semantic-release/semantic-release#363

**Comment by pvdlg** [comment] 2017-12-16 22:10
Fixed in the latest `semantic-release`

**Closed by pvdlg** 2017-12-16 22:10 UTC
Labels: bug
