### ISSUE TITLE
File not found and no environment variables set in Travis

### ISSUE THREAD

**Issue by roderik** [semantic-release/cli#196] opened 2018-03-10 21:34 UTC
```
[roderik@moneta ~/Development/databrokerdao-data-gateway](master *%)$ semantic-release-cli setup
? Is the GitHub repository private? Yes
? What is your npm registry? https://registry.npmjs.org/
? What is your npm username? xxx
? What is your GitHub username? xxx
? What is your GitHub two-factor authentication code? xxx
? What CI are you using? Travis CI Pro
ERR! semantic-release { file: 'not found' }
```

Happens with all my repo's. Any idea what could be wrong?

**Comment by gr2m** [comment] 2018-03-11 00:01
unfortunately no. Could you please run `npm_config_loglevel=verbose semantic-release-cli setup`? That should log some information useful for debugging

**Comment by theednaffattack** [comment] 2018-03-11 00:09
```bash
I'm getting:

```
info semantic-release Successfully created GitHub token.
? What CI are you using? Travis CI
info semantic-release Could not load Travis CI config for endpoint.
info semantic-release Syncing repositories...
ERR! semantic-release { file: 'not found' }
verb semantic-release Writing `package.json`.
info semantic-release Done.
```

Which seems related to this: https://github.com/semantic-release/cli/issues/28
I'm still learning so I don't know how to address this issue.

**Comment by roderik** [comment] 2018-03-11 07:00
Retried the repo (though i set the env vars manually yesterday) and it worked now. Will use the log level increase to get you a useful log.

**Comment by gr2m** [comment] 2018-03-19 21:22
When you run with `npm_config_loglevel=verbose` it will log the detected git URL, e.g. 

```
verb semantic-release Detected git url: https://github.com/octokit/routes.git
```

I just run into this and the problem was that I renamed the repository, but didn’t update the URLs in my package.json file. 

This is probably a case we can catch and provide a better error message for, PRs welcome :)

**Comment by timiscoding** [comment] 2018-04-04 00:57
@gr2m I renamed my repo and forgot to update my url too. thanks for reminding me! 

Also, if you're new to TravisCI like I am, you have to go to https://travis-ci.org and create an account that will ask you to link your github to travis. Once that was done, I got past the `What CI are you using?` step.

**Comment by harrison-ifeanyichukwu** [comment] 2018-06-13 15:43
Hello guys, the cause of this whole problem is on github username. `Travis ci` differentiates between username case format, unlike github, for instance, 

To github, `Harrison-ifeanyichukwu`  is the same as `harrison-ifeanyichukwu` but not to travis ci. 

When semantic release asks for your username, you will most probably supply your username in lowercase all through, (this is the problem). Semantic release will send this to github, and logs in freely, creates the api key successfully, but when the time comes to authenticate with travis, travis does not recognise the username and that is it.

**solution**
-  change your github username to all lowercase, go to your travis profile portal and sync.

**Or**
- supply your username as it is in your travis profile page during semantic release credential dialogs.

This has been a major problem for me, I had to dig deeper by installing [Travis Ruby Client](https://github.com/travis-ci/travis.rbTravis) on my ubuntu, and when i ran `travis init` on my project folder, i got this error message
```
repository not known to https://api.travis-ci.org/: harrison-ifeanyichukwu/forensic-js
```

This is the reason for the error message
```
info semantic-release Could not load Travis CI config for endpoint.
```

**Comment by gr2m** [comment] 2018-06-13 22:29
We amended the README via https://github.com/semantic-release/cli/pull/219, so I assume we can close this now?

**Closed by gr2m** 2018-06-13 22:29 UTC
Labels: cli, help wanted
