### ISSUE TITLE
Why would it start with 1.0.0

### ISSUE THREAD

**Issue by MiguelMadero** [semantic-release/cli#96] opened 2016-11-19 16:04 UTC
I had an addon working at 0.1.0, after installing this and merging to master, the version was bumped to 1.0.0, but I was expecting it to go to 0.2.0 since it only had `feat` and `fix`

**Comment by pvdlg** [comment] 2017-12-16 22:14
You can find more details about this choice in [Introduction to SemVer](https://blog.greenkeeper.io/introduction-to-semver-d272990c44f2)

**Comment by pvdlg** [comment] 2017-12-16 22:14
Duplicate of semantic-release/semantic-release#532

**Closed by pvdlg** 2017-12-16 22:14 UTC
