### ISSUE TITLE
Better error message when Organisation access is missing

### ISSUE THREAD

**Issue by davidpfahler** [semantic-release/cli#1] opened 2015-07-28 15:56 UTC
Thanks for this amazing cli! It works super well and maybe we can improve it a bit further.

I set up a repo with `semantic-release-cli setup` for an organisation to which Travis didn't yet have access, so I received the following error message:

```
ERR! semantic-release Could not get repository on Travis CI. { file: 'not found' }
ERR! semantic-release { file: 'not found' }
```

While I instantly realised that I had to set the Organisation up in Travis, this might not be obvious to all users. As @boennemann told me, the tokens are set up automatically as long as Organisation access is granted, so as far as I understand, this issue can only occur when the Organisation access is missing. If that is the case, can we let the user know and point them to the URL where they can learn how to grant this access?

**Comment by boennemann** [comment] 2015-07-28 15:57
Pinging @christophwitzko here.

**Comment by boennemann** [comment] 2015-07-28 15:59
Relevant code: https://github.com/semantic-release/cli/blob/master/src/lib/travis.js#L126

**Comment by Inkdpixels** [comment] 2016-05-31 09:13
Just for reference and in case someone else is having this problem in the future. 

I stumbled upon this issue with the exact same error message, but it was caused due to an invalid git repository URL in the package.json. 

Maybe we should put up some FAQ for this error?

**Comment by pvdlg** [comment] 2017-12-16 22:27
Duplicate of #88

**Closed by pvdlg** 2017-12-16 22:27 UTC
